name: secret
version: "0.1"
author: Nami W. <namiheike@gmail.com>
about: A secret command in your terminal

# args:

subcommands:
  - auth:
      about: TODO
  - notes:
      about: TODO
      subcommands:
        - new:
            about: create a new note
            args:
              - title:
                  help: TODO
                  required: true
        - list:
            about: list all notes
